# Generated by Django 3.2.15 on 2022-08-18 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='codeDDD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'DDD',
                'verbose_name_plural': 'DDDs',
            },
        ),
        migrations.CreateModel(
            name='PhonePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('time_limit', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Plano de Telefone',
                'verbose_name_plural': 'Planos de Telefone',
            },
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax', models.DecimalField(decimal_places=2, max_digits=5)),
                ('destiny', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destiny', to='phone_plans.codeddd')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='phone_plans.codeddd')),
            ],
        ),
    ]
