# Generated by Django 3.2.15 on 2022-08-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_plans', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codeddd',
            old_name='name',
            new_name='city',
        ),
        migrations.AddField(
            model_name='codeddd',
            name='state',
            field=models.CharField(default='SP', max_length=2),
            preserve_default=False,
        ),
    ]
